[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci --legacy-peer-deps || npm install --legacy-peer-deps']

[phases.build]
cmds = ['NEXT_TELEMETRY_DISABLED=1 NODE_OPTIONS=\"--max_old_space_size=1024\" npm run build']

[start]
cmd = 'npm run start'

