import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BackToTopButton from "@/components/BackToTopButton";
import MaintenanceGate from "@/components/MaintenanceGate";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className="antialiased overflow-x-hidden">
        <MaintenanceGate />
        <Navbar />
        {children}
        <BackToTopButton />
      </body>
    </html>
  );
}
