#!/bin/bash

echo "🚀 修復 Railway 前端 API 連接問題"
echo "=================================="
echo ""

# 後端服務 URL
BACKEND_URL="https://tattoo-crm-production-413f.up.railway.app"

echo "📋 問題分析："
echo "• 前端嘗試連接：https://tattoo-crm-backend.up.railway.app（不存在）"
echo "• 實際後端 URL：$BACKEND_URL"
echo "• 解決方案：設置 NEXT_PUBLIC_API_URL 環境變數"
echo ""

echo "🔧 解決方案："
echo ""

echo "方法 1：使用 Railway CLI（推薦）"
echo "--------------------------------"
echo "1. 安裝 Railway CLI："
echo "   npm install -g @railway/cli"
echo ""
echo "2. 登入 Railway："
echo "   railway login"
echo ""
echo "3. 連接到前端專案："
echo "   railway link"
echo ""
echo "4. 設置環境變數："
echo "   railway variables --set \"NEXT_PUBLIC_API_URL=$BACKEND_URL\""
echo ""

echo "方法 2：手動設置（Railway Dashboard）"
echo "------------------------------------"
echo "1. 登入 Railway Dashboard：https://railway.app"
echo "2. 選擇前端專案：tattoo-crm-production"
echo "3. 進入 Variables 標籤"
echo "4. 點擊 \"+ New Variable\""
echo "5. 設置："
echo "   Key: NEXT_PUBLIC_API_URL"
echo "   Value: $BACKEND_URL"
echo "6. 點擊 \"Add\""
echo ""

echo "方法 3：使用 curl 直接設置（需要 Railway API Token）"
echo "----------------------------------------------------"
echo "如果您有 Railway API Token，可以使用以下命令："
echo ""
echo "curl -X POST \\"
echo "  -H \"Authorization: Bearer YOUR_RAILWAY_TOKEN\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"name\": \"NEXT_PUBLIC_API_URL\", \"value\": \"$BACKEND_URL\"}' \\"
echo "  \"https://backboard.railway.app/graphql\""
echo ""

echo "⏱️  設置完成後："
echo "• Railway 會自動重新部署前端（2-3 分鐘）"
echo "• 前端將正確連接到後端服務"
echo "• 所有管理頁面將顯示數據"
echo ""

echo "🔍 驗證步驟："
echo "1. 等待部署完成"
echo "2. 訪問前端網站"
echo "3. 檢查管理頁面是否顯示數據"
echo "4. 測試登入功能"
echo ""

echo "📞 如果遇到問題："
echo "• 檢查 Railway Dashboard 中的部署日誌"
echo "• 確認環境變數已正確設置"
echo "• 驗證後端服務是否正常運行"
echo ""

echo "✅ 準備就緒！請選擇上述方法之一來設置環境變數。"
