#!/bin/bash

echo "🚀 Railway 資料同步自動化腳本"
echo "=================================="
echo ""

# Railway 後端專案名稱
BACKEND_PROJECT="Tattoo-crm-backend"
BACKEND_URL="https://tattoo-crm-production-413f.up.railway.app"

echo "📋 資料同步計劃"
echo "• 目標：Railway 後端資料庫"
echo "• 來源：本地後端完整測試數據"
echo "• 方法：使用 start-prod.js 自動種子系統"
echo ""

echo "🔧 步驟 1：設置 Railway 環境變數"
echo "=================================="
echo ""
echo "請在 Railway Dashboard 中設置以下環境變數："
echo ""
echo "專案：$BACKEND_PROJECT"
echo "URL：https://railway.app"
echo ""
echo "環境變數："
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. RUN_SEED=true"
echo "   說明：啟用資料庫種子數據導入"
echo ""
echo "2. PROTECT_REAL_DATA=false"
echo "   說明：允許覆蓋現有資料（測試環境）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📝 設置步驟："
echo "1. 登入 Railway Dashboard"
echo "2. 選擇專案：$BACKEND_PROJECT"
echo "3. 進入 Variables 標籤"
echo "4. 點擊 \"+ New Variable\""
echo "5. 添加 RUN_SEED=true"
echo "6. 添加 PROTECT_REAL_DATA=false"
echo "7. 點擊 \"Deploy\" 或等待自動部署"
echo ""

echo "🔧 步驟 2：觸發 Railway 部署"
echo "=================================="
echo ""
echo "方法 1：透過環境變數自動觸發（推薦）"
echo "• 設置環境變數後，Railway 會自動重新部署"
echo "• 部署過程中，start-prod.js 會自動執行種子數據導入"
echo ""
echo "方法 2：手動觸發部署"
echo "• 在 Railway Dashboard 中點擊 \"Redeploy\""
echo ""

echo "⏱️ 預計時間"
echo "=================================="
echo "• 設置環境變數：2 分鐘"
echo "• Railway 部署：3-5 分鐘"
echo "• 資料導入：1-2 分鐘"
echo "• 總計：6-9 分鐘"
echo ""

echo "🔍 驗證步驟"
echo "=================================="
echo ""
echo "部署完成後，驗證資料是否成功導入："
echo ""
echo "1. 檢查服務項目："
echo "   curl $BACKEND_URL/services | jq length"
echo "   預期：應該返回數字 > 0"
echo ""
echo "2. 檢查刺青師："
echo "   curl $BACKEND_URL/artists | jq length"
echo "   預期：應該返回數字 > 0"
echo ""
echo "3. 檢查分店統計："
echo "   curl $BACKEND_URL/branches/public | jq '.[0]._count'"
echo "   預期：artists, orders, appointments 應該 > 0"
echo ""

echo "⚠️ 重要提醒"
echo "=================================="
echo ""
echo "1. 這將覆蓋 Railway 資料庫中的現有資料"
echo "2. 確保這是測試環境，不是正式環境"
echo "3. 導入完成後，建議將 RUN_SEED 設為 false"
echo "   以避免下次部署時重複導入"
echo ""

echo "📞 如果遇到問題"
echo "=================================="
echo ""
echo "檢查 Railway 部署日誌："
echo "• 登入 Railway Dashboard"
echo "• 選擇專案：$BACKEND_PROJECT"
echo "• 進入 Deployments 標籤"
echo "• 查看最新部署的日誌"
echo ""
echo "常見問題："
echo "• 如果看到 Prisma migration 錯誤："
echo "  → 確認 DATABASE_URL 正確設置"
echo "  → 確認 Postgres 服務正常運行"
echo ""
echo "• 如果看到 seed 執行失敗："
echo "  → 檢查 RUN_SEED 是否設為 'true'"
echo "  → 檢查 PROTECT_REAL_DATA 是否設為 'false'"
echo "  → 查看錯誤訊息以確定具體問題"
echo ""

echo "✅ 準備就緒！"
echo "=================================="
echo ""
echo "請按照上述步驟操作，完成後告訴我，我會幫您驗證結果。"
echo ""
