#!/bin/bash

echo "🔄 強制 Railway 後端重新執行種子數據"
echo "======================================"
echo ""
echo "請按照以下步驟操作："
echo ""
echo "1. 訪問 Railway Dashboard："
echo "   https://railway.app/dashboard"
echo ""
echo "2. 選擇 'tattoo-crm-backend' 服務"
echo ""
echo "3. 點擊 'Variables' 標籤"
echo ""
echo "4. 確認以下環境變數設置："
echo "   - RUN_SEED=true"
echo "   - RESET_DATABASE=true"
echo "   - PROTECT_REAL_DATA=false"
echo ""
echo "5. 如果這些環境變數已經設置，請手動觸發重新部署："
echo "   - 點擊 'Deployments' 標籤"
echo "   - 點擊 'Redeploy' 按鈕"
echo ""
echo "6. 等待部署完成（約 3-5 分鐘）"
echo ""
echo "7. 檢查部署日誌，確認看到以下訊息："
echo "   - '🌱 執行資料庫 seeding...'"
echo "   - '✅ 資料庫種子數據導入成功'"
echo ""
echo "如果重新部署後問題仍然存在，可能需要："
echo "- 刪除 Railway PostgreSQL 數據庫"
echo "- 創建新的 PostgreSQL 數據庫"
echo "- 重新部署後端服務"
echo ""

