-- Appointment V2 policy fields + NO_SHOW status

-- 1) Add new enum value NO_SHOW (Postgres enum generated by Prisma)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'AppointmentStatus') THEN
    -- add value if not exists
    IF NOT EXISTS (
      SELECT 1
      FROM pg_enum e
      JOIN pg_type t ON t.oid = e.enumtypid
      WHERE t.typname = 'AppointmentStatus' AND e.enumlabel = 'NO_SHOW'
    ) THEN
      ALTER TYPE "AppointmentStatus" ADD VALUE 'NO_SHOW';
    END IF;
  END IF;
END $$;

-- 2) Add policy tracking columns
ALTER TABLE "Appointment"
  ADD COLUMN IF NOT EXISTS "rescheduleCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "lastRescheduledAt" TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "rescheduleReason" TEXT,
  ADD COLUMN IF NOT EXISTS "canceledAt" TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "cancelReason" TEXT,
  ADD COLUMN IF NOT EXISTS "noShowAt" TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "noShowReason" TEXT;

-- 3) Add helpful index for slot queries
CREATE INDEX IF NOT EXISTS "Appointment_branchId_artistId_startAt_idx"
  ON "Appointment"("branchId","artistId","startAt");


